### ISSUE TITLE
How can I change Bars color?

### ISSUE THREAD

**Issue by maxxhount** [joadan/Blazor-ApexCharts#10]
I  would like to change Bars colors. This is my code
`<ApexChart TItem="OperationBarChartData" 
        Title="" 
        Options="GetOptions()"
        ChartType="ChartType.Bar">

    <ApexSeries TItem="OperationBarChartData" 
        Items="Data" Name="Encaissement" 
        XValue="@(o => o.Month)"
        YAggregate="@(o => o.Sum(o => o.IncomeAmount))" 
        OrderByDescending="e=>e.Y" />

    <ApexSeries TItem="OperationBarChartData" 
        Items="Data" Name="Décaissement" 
        XValue="@(o => o.Month)"
        YAggregate="@(o => o.Sum(o => o.ExpenseAmount))" 
        OrderByDescending="e=>e.Y" />

</ApexChart>

@code {
    [Parameter]
    public List<OperationBarChartData> Data { get; set; }

    private ApexChartOptions<OperationBarChartData> GetOptions()
    {
        var options = new ApexChartOptions<OperationBarChartData>();
        **options.Colors = new List<string>{"#3699FF","#2670FF"};**
        return options;
    }
}`

When i remove the Options, my bars display with the default colors (blue and green). 
![image](https://user-images.githubusercontent.com/5090950/101664469-2a81b080-3a4c-11eb-94bf-ce1ff52a2ebc.png)

But when I add Options nothing display.
![image](https://user-images.githubusercontent.com/5090950/101664870-a11eae00-3a4c-11eb-8fc9-3346fa8bde46.png)

How can I change the bar colors?

**Comment by joadan** [comment]
Hi,

Check this example [StatisticsLineChart.razor](https://github.com/joadan/TabBlazor/blob/master/docs/Tabler.Docs/Components/Snippets/Statistics/StatisticsLineChart.razor) in the TabBlazor repo.
