### ISSUE TITLE
It should be possible to the set the color for a series as an attribute

### ISSUE THREAD

**Issue by joadan** [joadan/Blazor-ApexCharts#11]
We should make it possible to set the color of the series as an attribute on the series. 
Currently it's only possible using the options.

**Comment by joadan** [comment]
#10

**Comment by maxxhount** [comment]
Hi @joadan . Any update about this request??

**Comment by joadan** [comment]
Hi,

I have release a new version with support to to set Stroke options on each series, check example at [Series Options](https://joadan.github.io/Blazor-ApexCharts/series-options)

Please let me know if this resolves your issue.

Regards Joakim

**Comment by joadan** [comment]
Clean up
