### ISSUE TITLE
StackType The100 is not working

### ISSUE THREAD

**Issue by larsjoR** [joadan/Blazor-ApexCharts#14]
Hi,

Just noticed that the stack type "The100" is not being translated correctly upon initializing the JS Chart.  
Quick repro:

`            
_options = private readonly ApexChartOptions<MyData> _options = new();
_options.Chart = new Chart
            {
                Stacked = true,
                Type = ChartType.Bar,
                StackType = StackType.The100
            };
`

Using debug = true, I notice that the output is: 
![bilde](https://user-images.githubusercontent.com/9251481/117118047-8ef13380-ad90-11eb-95e4-ab3532d1c009.png)

I believe this is related to the fact that this is an enum, and it's just being passed in with the enum text values "Normal/The100".
The properiate type setting for The100 should be "100%". 

I'm not sure if you appreciate PR's or if you'd just like bugs to be reported here, but here you go :)

**Comment by joadan** [comment]
Hello,

Thank you for reporting this. 
PR's are more then welcome, but if you like could fix it, just let me know.

I used the apexchart typescript definition to automatic generate the option class, but I had to do quite a lot of manuall work to get it going, I guess I missed this one.

**Comment by larsjoR** [comment]
Hi again! 

No worries, I totally understand. You have been doing some great work here by the way!
If you fix this one, i'll try to PR if I find other issues i can't work around 👍

**Comment by joadan** [comment]
Glad you like It....

I just whish that I had more time to spend on it.. but I guess that is just the way things are..
I'll try to get a fix out this week.

**Comment by joadan** [comment]
Fixed in version v0.2.3-alpha
