### ISSUE TITLE
Typo in DatetimeUTC option for XAxisLabels

### ISSUE THREAD

**Issue by adamico2412** [joadan/Blazor-ApexCharts#16]
Typo in DatetimeUTC chart option forces all DateTime axes to use UTC.

From apex docs: https://apexcharts.com/docs/options/xaxis/#datetimeUTC

Blazor-ApexCharts: https://github.com/joadan/Blazor-ApexCharts/blob/c9144e7912427c170b1b2cc447c176a02481bbfa/src/Blazor-ApexCharts/Models/ApexChartOptions.cs#L1290

**Comment by joadan** [comment]
Thank you, I have release a new nuget 0.2.4-alpha

**Comment by adamico2412** [comment]
Thank you very much!
