### ISSUE TITLE
Add support for formatters 

### ISSUE THREAD

**Issue by joadan** [joadan/Blazor-ApexCharts#20]
Currently it's not possible to pass in a formatter.

**Comment by ponchautf** [comment]
Hi @joadan, 
did you have an idea when this will be available?
and did you think that it will be possible to put HTML in the formatter (it's not clear on the Apex doc if formatter support HTML)

Thanks

**Comment by joadan** [comment]
Hi, 
The way I understand it is that formatters are the ability to provide an Javascript function to format the value.

I can't really promise when this will be added, but it is really something I would like to add.
Let me know if you are interested to create a PR, if not I'll try to look at this as soon as I have time.

**Comment by joadan** [comment]
I thing the ToolTip.Custom is an example where you can provide Html to render a tooltip. https://codepen.io/apexcharts/pen/NBdyvV

Unfortunately this is currently not supported in Blazor-ApexCharts

**Comment by ponchautf** [comment]
@joadan I’ve forked your repo to take a look and understand how  your package works.
I will try to find some free time to try something.

meanwhile, I found an interesting post on SO that explain how to inject functions into json.

https://stackoverflow.com/questions/6663378/serializing-a-function-as-a-parameter-in-json-using-c-sharp

This is probably a good starting point. Hope that help a little bit

**Comment by joadan** [comment]
Hi,

Current implementation is using System.Text.Json and with that I don't believe it's possible, at least not in .Net 5 but I believe will be available .net 6 https://github.com/dotnet/runtime/issues/1784 
We could turn to NewtonSoft but I prefer not to, left is the option to manually adjust the serialized string before pass it to down.

I'm actually looking at this  right now...

**Comment by joadan** [comment]
Fixed in 0.4.0-alpha

The issue was not how to serialize to json it but rather how to convert the serialized string to a javascript object when it had formatters (functions)

**Comment by ponchautf** [comment]
Yeah, thank a lot for your quick fix.
It's so exceptional to get a so fast response.
