### ISSUE TITLE
Cannot set the x axis border height

### ISSUE THREAD

**Issue by ponchautf** [joadan/Blazor-ApexCharts#22]
Hi,

It seems that it's not possible to set the x axis border height.

When I try to set the border as this:

```
 AxisBorder = new XaxisAxisBorder()
            {
                StrokeWidth = 2,
                OffsetX = -10,
                OffsetY = -1,
                Show = true,
                Color = "#C8CADA"
            },
```
            
All seems working exept the StrokeWidth.

Reading the apexChart doc, it seem the the x axis have a height option but not a stroke width.

Could you take a look at this?

Thanks

**Comment by joadan** [comment]
Thanks, this is now fixed in 0.4.0-alpha
