### ISSUE TITLE
Update chart with new data

### ISSUE THREAD

**Issue by Beltzac** [joadan/Blazor-ApexCharts#5]
Hi, what is the intended way to update a chart with new data and have it re-render? I cant find a way to do it. Like bind a variable to ApexSeries Items, or an Update() method.

**Comment by joadan** [comment]
Hi,

The plan is to be able to have the chart automatically update if the data changes.
I have started the work and should have an update out in a day or two. 
In addition to that it will be possible to turnoff automatic update and manually trigger an update using a Render() method.

**Comment by joadan** [comment]
Hello,

I have now updated the code to support this. I have also added a sample [render chart](https://joadan.github.io/Blazor-ApexCharts/render-chart) to show it in action.
