### ISSUE TITLE
Change chart aspect ratio

### ISSUE THREAD

**Issue by JohnSully** [joadan/Blazor-ApexCharts#6]
Charts seem to have a fixed width/height ratio and I haven't found a way to change this yet.  Is it NYI or am I just missing the option?

Edit: Issue seems to be a min-height setting inside the control itself.  This is preventing me from limiting its height from the container DIV.

**Comment by joadan** [comment]
The blazor wrapper component should not add any min-height setting so It must come from the apex chart itselft. Not sure if there is anything I can do here, but if you provide a way to reproduce I could have a look.

**Comment by joadan** [comment]
Clean up
