### ISSUE TITLE
Brush chart

### ISSUE THREAD

**Issue by Eric898989** [joadan/Blazor-ApexCharts#7]
Could you provide a example of brush chart like the one below with your lib?

![image](https://user-images.githubusercontent.com/12022659/85234731-c3296300-b40f-11ea-9c1e-4202895465c0.png)

**Comment by Eric898989** [comment]
Sorry I mixed Id and CharId ! It works now

**Comment by ppvario** [comment]
> Sorry I mixed Id and CharId ! It works now

Can you share your code? I am trying to get this to work on blazor too
