### ISSUE TITLE
ChartExamples: An unhandled error has occurred

### ISSUE THREAD

**Issue by win32nipuh** [joadan/Blazor-ApexCharts#8]
I run the ChartExamples project and receive in the browser

Loading...
An unhandled error has occurred. Reload 🗙
and Page source

`

  |
  |  
  |
  |
  |
  | <title>Chart Samples</title>
  |
  |
  |
  |
  |  
  |
  | Loading...
  |  
  |
  | <script type="text/javascript">
  | // Single Page Apps for GitHub Pages
  | // https://github.com/rafrex/spa-github-pages
  | // Copyright (c) 2016 Rafael Pedicini, licensed under the MIT License
  | // ----------------------------------------------------------------------
  | // This script checks to see if a redirect is present in the query string
  | // and converts it back into the correct url and adds it to the
  | // browser's history using window.history.replaceState(...),
  | // which won't cause the browser to attempt to load the new url.
  | // When the single page app is loaded further down in this file,
  | // the correct url will be waiting in the browser's history for
  | // the single page app to route accordingly.
  | (function (l) {
  | if (l.search) {
  | var q = {};
  | l.search.slice(1).split('&').forEach(function (v) {
  | var a = v.split('=');
  | q[a[0]] = a.slice(1).join('=').replace(/and/g, '&');
  | });
  | if (q.p !== undefined) {
  | window.history.replaceState(null, null,
  | l.pathname.slice(0, -1) + (q.p || '') +
  | (q.q ? ('?' + q.q) : '') +
  | l.hash
  | );
  | }
  | }
  | }(window.location))
  | </script>
  |
  |  
  |

  | An unhandled error has occurred.
  | Reload
  | 🗙
  |

  |  
  |  
  | <script src="_framework/blazor.webassembly.js"></script>
  | <script src="_content/Blazor-ApexCharts/js/apex-charts.min.js"></script>
  | <script src="_content/Blazor-ApexCharts/js/blazor-apex-charts.js"></script>
  |
  |  
  |
 
`

How to fix it and run the samples?

**Comment by joadan** [comment]
Hello,

I have not experienced this myself.
Do you get this error running locally or at [Demo](https://joadan.github.io/Blazor-ApexCharts/)?
What browser are you using?
Any more info in the console?

**Comment by Oleg26Dev** [comment]
It is me too. 
It is local demo, I have run it in VS 2019, the browser is Chrome.

**Comment by joadan** [comment]
Could it be the url.. when you start your application it should start: https://localhost:44380/Blazor-ApexCharts 
I cant use the the root due to how github pages work.

**Comment by Oleg26Dev** [comment]
Ok, yes, it can be the reason, I will check it.

Btw, can I create 3D Pie and Charts using ApexCharts?

**Comment by joadan** [comment]
Clean up
