### ISSUE TITLE
Timeline Charts - multiple values in Y series

### ISSUE THREAD

**Issue by anako126n** [joadan/Blazor-ApexCharts#9]
Is it possible at this stage to create any of the timeline charts, for example, RangeBar?

This type of chart is expecting two values for every entry in  Y data series while YAggregate works with one.

**Comment by joadan** [comment]
Right now it's not possible but it should not be that hard to implement.
I don't have time right now but I keep it opened so we can track the progress.

You are more then welcome to create pull request.

**Comment by joadan** [comment]
Tracked in #24
